Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 172, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
het_test_probit(res_heckit.select_res)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[47], line 1[0m
[0;32m----> 1[0m [43mhet_test_probit[49m[43m([49m[43mres_heckit[49m[38;5;241;43m.[39;49m[43mselect_res[49m[43m)[49m

File [0;32m~/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/py4etrics/hetero_test.py:152[0m, in [0;36mhet_test_probit[0;34m(results)[0m
[1;32m    149[0m A [38;5;241m=[39m A[[38;5;241m-[39mnum_para:,:]
[1;32m    150[0m s [38;5;241m=[39m res_test[38;5;241m.[39mwald_test(A, scalar[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m    151[0m [38;5;28;01mreturn[39;00m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mH0: homoscedasticity[39m[38;5;130;01m\n[39;00m[38;5;124mHA: heteroscedasticity[39m[38;5;130;01m\n[39;00m[38;5;124m'[39m,
[0;32m--> 152[0m             [38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;124mWald test:[39m[38;5;124m'[39m, [38;5;124m"[39m[38;5;132;01m%#2.3f[39;00m[38;5;124m"[39m [38;5;241m%[39m [43ms[49m[38;5;241;43m.[39;49m[43mstatistic[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[[38;5;241m0[39m],
[1;32m    153[0m             [38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;124mp-value:[39m[38;5;124m'[39m, [38;5;124m"[39m[38;5;132;01m%#7.3f[39;00m[38;5;124m"[39m [38;5;241m%[39m s[38;5;241m.[39mpvalue, [38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;124mdf freedom:[39m[38;5;124m'[39m, [38;5;124m"[39m[38;5;132;01m%#3.0f[39;00m[38;5;124m"[39m [38;5;241m%[39m s[38;5;241m.[39mdf_denom)

[0;31mTypeError[0m: 'float' object is not subscriptable

