Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/runner/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/runner/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/runner/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/runner/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/runner/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/runner/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/runner/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import gapminder, linearmodels, lmdiag, matplotlib, numba, numpy, pandas, py4etrics, scipy, see, statsmodels, wooldridge
from platform import python_version

packages = ['Python','gapminder','linearmodels', 'lmdiag','matplotlib', 'numba', 'numpy','pandas', 'py4etrics', 'scipy','see', 'statsmodels', 'wooldridge']
versions = [python_version(),gapminder.__version__, linearmodels.__version__, '0.3.7', matplotlib.__version__, numba.__version__, numpy.__version__, pandas.__version__, py4etrics.__version__, scipy.__version__, see.__version__, statsmodels.__version__, wooldridge.__version__]

for pack, ver in zip(packages, versions):
    print('{0:14}{1}'.format(pack,ver))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-c71190dcc335>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mimport[0m [0mgapminder[0m[0;34m,[0m [0mlinearmodels[0m[0;34m,[0m [0mlmdiag[0m[0;34m,[0m [0mmatplotlib[0m[0;34m,[0m [0mnumba[0m[0;34m,[0m [0mnumpy[0m[0;34m,[0m [0mpandas[0m[0;34m,[0m [0mpy4etrics[0m[0;34m,[0m [0mscipy[0m[0;34m,[0m [0msee[0m[0;34m,[0m [0mstatsmodels[0m[0;34m,[0m [0mwooldridge[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mfrom[0m [0mplatform[0m [0;32mimport[0m [0mpython_version[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0mpackages[0m [0;34m=[0m [0;34m[[0m[0;34m'Python'[0m[0;34m,[0m[0;34m'gapminder'[0m[0;34m,[0m[0;34m'linearmodels'[0m[0;34m,[0m [0;34m'lmdiag'[0m[0;34m,[0m[0;34m'matplotlib'[0m[0;34m,[0m [0;34m'numba'[0m[0;34m,[0m [0;34m'numpy'[0m[0;34m,[0m[0;34m'pandas'[0m[0;34m,[0m [0;34m'py4etrics'[0m[0;34m,[0m [0;34m'scipy'[0m[0;34m,[0m[0;34m'see'[0m[0;34m,[0m [0;34m'statsmodels'[0m[0;34m,[0m [0;34m'wooldridge'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mversions[0m [0;34m=[0m [0;34m[[0m[0mpython_version[0m[0;34m([0m[0;34m)[0m[0;34m,[0m[0mgapminder[0m[0;34m.[0m[0m__version__[0m[0;34m,[0m [0mlinearmodels[0m[0;34m.[0m[0m__version__[0m[0;34m,[0m [0;34m'0.3.7'[0m[0;34m,[0m [0mmatplotlib[0m[0;34m.[0m[0m__version__[0m[0;34m,[0m [0mnumba[0m[0;34m.[0m[0m__version__[0m[0;34m,[0m [0mnumpy[0m[0;34m.[0m[0m__version__[0m[0;34m,[0m [0mpandas[0m[0;34m.[0m[0m__version__[0m[0;34m,[0m [0mpy4etrics[0m[0;34m.[0m[0m__version__[0m[0;34m,[0m [0mscipy[0m[0;34m.[0m[0m__version__[0m[0;34m,[0m [0msee[0m[0;34m.[0m[0m__version__[0m[0;34m,[0m [0mstatsmodels[0m[0;34m.[0m[0m__version__[0m[0;34m,[0m [0mwooldridge[0m[0;34m.[0m[0m__version__[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'gapminder'
ModuleNotFoundError: No module named 'gapminder'

